/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class CompanySchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'name', 'updatedAt'] as const
  $columns = CompanySchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare name: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class LoyaltyAccountSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'loyaltyProgramId', 'updatedAt', 'userId'] as const
  $columns = LoyaltyAccountSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare loyaltyProgramId: bigint | number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare userId: bigint | number
}

export class LoyaltyProgramSchema extends BaseModel {
  static $columns = [
    'active',
    'companyId',
    'createdAt',
    'id',
    'name',
    'rewardTitle',
    'stampsRequired',
    'updatedAt',
  ] as const
  $columns = LoyaltyProgramSchema.$columns
  @column()
  declare active: boolean
  @column()
  declare companyId: bigint | number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare name: string
  @column()
  declare rewardTitle: string
  @column()
  declare stampsRequired: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class NfcTagSchema extends BaseModel {
  static $columns = [
    'active',
    'createdAt',
    'id',
    'identifier',
    'lastAcceptedCounter',
    'updatedAt',
    'venueId',
  ] as const
  $columns = NfcTagSchema.$columns
  @column()
  declare active: boolean
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare identifier: string
  @column()
  declare lastAcceptedCounter: bigint | number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare venueId: bigint | number
}

export class StampSchema extends BaseModel {
  static $columns = [
    'createdAt',
    'id',
    'loyaltyAccountId',
    'nfcCounter',
    'nfcTagId',
    'updatedAt',
  ] as const
  $columns = StampSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare loyaltyAccountId: bigint | number
  @column()
  declare nfcCounter: bigint | number
  @column()
  declare nfcTagId: bigint | number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class UserSchema extends BaseModel {
  static $columns = [
    'createdAt',
    'email',
    'encryptedPassword',
    'id',
    'rememberCreatedAt',
    'resetPasswordSentAt',
    'resetPasswordToken',
    'updatedAt',
  ] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column({ serializeAs: null })
  declare encryptedPassword: string
  @column({ isPrimary: true })
  declare id: bigint | number
  @column.dateTime()
  declare rememberCreatedAt: DateTime | null
  @column.dateTime()
  declare resetPasswordSentAt: DateTime | null
  @column({ serializeAs: null })
  declare resetPasswordToken: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class VenueSchema extends BaseModel {
  static $columns = ['companyId', 'createdAt', 'id', 'name', 'updatedAt'] as const
  $columns = VenueSchema.$columns
  @column()
  declare companyId: bigint | number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare name: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}
